CREATE TABLE PessoasFisicas (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Nome NVARCHAR(150) NOT NULL,
  Telefone NVARCHAR(20) NULL,
  Email NVARCHAR(150) NOT NULL UNIQUE,
  SenhaHash NVARCHAR(255) NOT NULL,
  Latitude FLOAT NULL,
  Longitude FLOAT NULL,
  TipoResiduo NVARCHAR(50) NULL,
  QuantidadeKg DECIMAL(10,2) NULL,
  Observacoes NVARCHAR(500) NULL,
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Empresas (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  RazaoSocial NVARCHAR(150) NOT NULL,
  NomeContato NVARCHAR(150) NOT NULL,
  Telefone NVARCHAR(20) NOT NULL,
  Email NVARCHAR(150) NOT NULL UNIQUE,
  SenhaHash NVARCHAR(255) NOT NULL,
  Cnpj NVARCHAR(20) NULL,
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Residuos (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  PessoaFisicaId INT NOT NULL,
  TipoResiduo NVARCHAR(50) NULL,
  QuantidadeKg DECIMAL(10,2) NULL,
  Observacoes NVARCHAR(500) NULL,
  Latitude FLOAT NULL,
  Longitude FLOAT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
  FOREIGN KEY (PessoaFisicaId) REFERENCES PessoasFisicas(Id)
);
